---
- name: Install etckeeper early for change tracking
  apt:
    name: etckeeper
    state: present
    update_cache: yes

- name: Initialize etckeeper repository
  command: etckeeper init
  args:
    creates: /etc/.git

- name: Make initial etckeeper commit
  command: etckeeper commit "Initial commit before configuration"
  args:
    creates: /etc/.git/refs/heads/master
  ignore_errors: yes

- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: base_update_cache | bool

- name: Upgrade all packages
  apt:
    upgrade: dist
  when: base_upgrade_packages | bool

- name: Install essential packages
  apt:
    name: "{{ base_packages }}"
    state: present

- name: Install additional packages
  apt:
    name: "{{ extra_packages }}"
    state: present
  when: extra_packages | length > 0

- name: Set hostname
  copy:
    content: "{{ base_hostname }}\n"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'
  tags: hostname

- name: Generate hosts file from template
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags: hostname

- name: Configure /etc/fstab from template
  template:
    src: fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'
  tags: fstab
  notify: commit etckeeper changes
  vars:
    etckeeper_commit_message: "Configure fstab for {{ inventory_hostname }}"

- name: Configure timezone
  timezone:
    name: "{{ base_timezone }}"
  notify: Restart systemd-timesyncd

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ base_locales }}"
  notify: Restart systemd-localed

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    create: yes
    owner: root
    group: root
    mode: '0644'
  loop:
    - { key: 'LANG', value: '{{ base_lang }}' }
    - { key: 'LC_ALL', value: '{{ base_lc_all }}' }
  notify: Restart systemd-localed

- name: Set journald config
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart journald

- name: Configure system limits
  pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: "{{ base_max_open_files }}"

- name: Configure system limits (hard)
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: "{{ base_max_open_files }}"

- name: Set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ base_swappiness }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-base.conf
    reload: yes

- name: Configure ZFS-specific sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-zfs.conf
    reload: yes
  loop: "{{ zfs_sysctl_settings | default([]) }}"
  when: zfs_sysctl_settings is defined

- name: Create system users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password_hash | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default([]) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default('/home/' + item.name) }}"
    create_home: "{{ item.create_home | default(true) }}"
    append: yes
    state: present
  loop: "{{ system_users | default([]) }}"
  when: system_users is defined
