---
# Note: When decrypting a file, SOPS will look for ~/.ssh/id_ed25519 and falls back to ~/.ssh/id_rsa
# So I needed to 'export SOPS_AGE_SSH_PRIVATE_KEY_FILE=~/.ssh/id_techiebod'
creation_rules:
  - path_regex: ^config/secrets\.sops\.yaml$
    encrypted_regex: '^(users|secrets)$'
    age: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGl7Dr6eZTG7KA21Dm293hW0Mh8hsr5PawiQKMOzy7s'
