---
# Docker installation defaults

# Docker repository configuration
docker_apt_repository: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

# Docker packages to install
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Docker service configuration
docker_start_service: true
docker_enable_service: true

# User configuration (empty by default, set in host_vars if needed)
docker_users: []
