---
# Global variables loaded from config files
# This keeps user-specific configuration separate from reusable roles

# Load user environment variables from config/user.env
# These can be overridden in host-specific files if needed
base_hostname: "{{ lookup('env', 'HOSTNAME') | default('zfs-system') }}"
base_timezone: "{{ lookup('env', 'TIMEZONE') | default('UTC') }}"
base_locale: "{{ lookup('env', 'LOCALE') | default('en_US.UTF-8') }}"

# Derive related locale settings from the main locale
base_locales:
  - "{{ base_locale }}"
  - "en_US.UTF-8"  # Always include as fallback
  - "C.UTF-8"      # Always include as fallback

base_lang: "{{ base_locale }}"
base_lc_all: "{{ base_locale }}"

# Generic system configuration (safe defaults for any user)
base_update_cache: true
base_upgrade_packages: false  # User can override this
base_swappiness: 1            # Low for ZFS systems
base_max_open_files: 65536

# Essential packages for ZFS systems (generic, no user preferences)
base_packages:
  - curl
  - wget
  - vim
  - htop
  - tree
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg
  - software-properties-common
  - locales
  - tzdata
  - util-linux-extra
  - git  # For etckeeper

# Optional feature flags (can be overridden per host)
install_docker: true
install_samba: false
install_zfs_tools: true

# ZFS-specific packages (only installed if install_zfs_tools is true)
zfs_packages:
  - zfs-auto-snapshot
  - smartmontools
  - nvme-cli
  - hdparm

# SSH security defaults
base_ssh_permit_root_login: "no"
base_ssh_password_authentication: "no"
base_ssh_pubkey_authentication: "yes"

# Network configuration for hosts file
# Define your local network hosts here
network_hosts:
  blackbox: "192.168.123.135"  # Current DHCP address on main network
  babybox: "192.168.123.11"    # Expected address for babybox
  pibox: "192.168.123.12"      # Expected address for pibox

# High-bandwidth private network for machine-to-machine communication
# Used for ZFS replication and other high-throughput operations
# Define your private network hosts here
private_network_hosts:
  blackbox.private: "10.0.0.1"
  babybox.private: "10.0.0.2"
  # Add more private network connections as needed
