---
# Variables specific to ZFS systems
# These are optimizations and configurations specific to ZFS setups

# ZFS-optimized system settings
base_swappiness: 1  # Even lower for ZFS
vm_dirty_ratio: 5
vm_dirty_background_ratio: 2

# Additional ZFS packages
base_packages:
  - curl
  - wget
  - vim
  - htop
  - tree
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg
  - software-properties-common
  - locales
  - tzdata
  - git
  - zfs-auto-snapshot
  - smartmontools
  - nvme-cli
  - hdparm
  - sanoid  # ZFS snapshot management
  - mbuffer  # For faster ZFS sends

# ZFS-specific sysctl settings
zfs_sysctl_settings:
  - name: vm.swappiness
    value: "{{ base_swappiness }}"
  - name: vm.dirty_ratio
    value: "{{ vm_dirty_ratio }}"
  - name: vm.dirty_background_ratio
    value: "{{ vm_dirty_background_ratio }}"

# Enable ZFS tools by default for this group
install_zfs_tools: true
