---
# Syncoid role handlers

- name: check if systemd is running as PID 1 for syncoid
  command: ps -p 1 -o comm=
  register: syncoid_handler_pid1_check
  changed_when: false
  failed_when: false

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: syncoid_handler_pid1_check.stdout == "systemd"

- name: restart syncoid timer
  systemd:
    name: sync-ZFS.timer
    state: restarted
    enabled: yes
  when: (syncoid_enable | default(false)) and (syncoid_handler_pid1_check.stdout == "systemd")
