---
# Syncoid role handlers

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart syncoid timer
  systemd:
    name: sync-ZFS.timer
    state: restarted
    enabled: yes
  when: syncoid_enable | default(false)
