---
# Sanoid ZFS snapshot management

- name: Install sanoid package
  package:
    name: sanoid
    state: present
  tags: [sanoid]

- name: Create sanoid configuration directory
  file:
    path: /etc/sanoid
    state: directory
    mode: '0755'
  tags: [sanoid]

- name: Configure sanoid
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    backup: yes
  notify: restart sanoid
  tags: [sanoid]

- name: Reload systemd daemon to recognize new services
  systemd:
    daemon_reload: yes
  tags: [sanoid]

- name: Enable and start sanoid timer
  systemd:
    name: sanoid.timer
    enabled: yes
    state: started
  tags: [sanoid]
