---
# Sanoid ZFS snapshot management

- name: Install sanoid package
  package:
    name: sanoid
    state: present
  tags: [sanoid]

- name: Create sanoid configuration directory
  file:
    path: /etc/sanoid
    state: directory
    mode: '0755'
  tags: [sanoid]

- name: Configure sanoid
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    backup: yes
  notify: restart sanoid
  tags: [sanoid]

- name: Check if systemd is running as PID 1
  command: ps -p 1 -o comm=
  register: pid1_check
  changed_when: false
  failed_when: false

- name: Reload systemd daemon to recognize new services
  ansible.builtin.systemd:
    daemon_reload: true
  when: pid1_check.stdout == "systemd"
  tags: [sanoid]

- name: Enable and start sanoid timer
  systemd:
    name: sanoid.timer
    enabled: yes
    state: started
  when: pid1_check.stdout == "systemd"
  tags: [sanoid]
