network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: true
    # Additional interfaces should be configured in host_vars
    # Example:
    # eno2:
    #   dhcp4: false
    #   addresses: [10.0.0.x/24]
