---
# Configuration for main ZFS server
base_hostname: blackbox
base_timezone: "Europe/London"
base_locale: "en_GB.UTF-8"
base_locales:
  - "en_GB.UTF-8"
  - "en_US.UTF-8" 
  - "C.UTF-8"
base_lang: "en_GB.UTF-8"
base_lc_all: "en_GB.UTF-8"

# Network configuration specific to blackbox
network_config:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      emit-lldp: true
      dhcp4: true
    priv0:
      match:
        macaddress: d8:bb:c1:9a:39:ff
      set-name: priv0
      emit-lldp: true
      dhcp4: false
      mtu: 9000
      addresses: [10.0.0.1/24]

# Docker configuration (geerlingguy.docker role)
docker_install_compose: true
docker_users:
  - henry

# Docker daemon configuration
docker_daemon_options:
  metrics-addr: "0.0.0.0:9323"
  experimental: true
  dns:
    - "8.8.8.8"
    - "8.8.4.4"
  log-driver: "journald"
  log-opts:
    tag: "Container: {{ '{{' }}.Name{{ '}}' }}"
  data-root: "/var/tmp/docker"

# Additional packages for this server (if any)
extra_packages:
  - ncdu  # Disk usage analyzer
