---
# Configuration for main ZFS server
base_hostname: blackbox

# Network configuration specific to blackbox
network_config:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      emit-lldp: true
      dhcp4: true
    priv0:
      match:
        macaddress: d8:bb:c1:9a:39:ff
      set-name: priv0
      emit-lldp: true
      dhcp4: false
      mtu: 9000
      addresses: [10.0.0.1/24]

# Docker configuration (geerlingguy.docker role)
docker_install_compose: true
docker_users:
  - henry

# Docker daemon configuration
docker_daemon_options:
  metrics-addr: "0.0.0.0:9323"
  experimental: true
  dns:
    - "8.8.8.8"
    - "8.8.4.4"
  log-driver: "journald"
  log-opts:
    tag: "Container: {{ '{{' }}.Name{{ '}}' }}"
  data-root: "/var/tmp/docker"

# Additional packages for this server (if any)
extra_packages:
  - ncdu  # Disk usage analyzer
  - prometheus-node-exporter
  - sanoid
  - unattended-upgrades
  - avahi-daemon
  - avahi-utils

# System users to create
system_users:
  - name: henry
    password_hash: "{{ secrets.users.henry.password_hash }}"
    uid: 1000  # Preserve existing UID
    group: henry  # Primary group
    groups: ["adm", "docker", "sudo"]  # Essential groups for system access
    shell: /bin/zsh  # Ensure zsh is the default shell
    home: /home/henry  # Explicit home directory (on ZFS partition)
    create_home: true  # Ensure home exists but won't overwrite existing
  - name: timemachine
    password_hash: "{{ secrets.users.timemachine.password_hash }}"
    shell: /bin/false
    groups: []
  - name: paperless
    password_hash: "{{ secrets.users.paperless.password_hash }}"
    shell: /bin/false
    groups: []


# Enable Samba file server
install_samba: true

# Enable share-specific include files
samba_shares_include_files: true

# Samba configuration for TimeMachine and file sharing
samba_apple_extensions: true
samba_workgroup: WORKGROUP
samba_server_string: "%h server (Samba, Ubuntu)"
samba_netbios_name: "{{ base_hostname }}"
samba_log: /var/log/samba.log
samba_log_level: 2
samba_log_size: 1000
samba_server_min_protocol: SMB2_02
samba_enable_netbios: true
samba_mdns_name: netbios
samba_load_homes: true

# Global Samba configuration extras for Apple/TimeMachine support
samba_global_config_extras: |
  # Apple/macOS optimizations
  vfs objects = fruit streams_xattr
  fruit:appl = yes
  fruit:nfs_aces = no
  fruit:copyfile = no
  fruit:metadata = stream
  fruit:model = MacSamba
  fruit:posix_rename = yes
  fruit:veto_appledouble = no
  fruit:wipe_intentionally_left_blank_rfork = yes
  fruit:delete_empty_adfiles = yes
  
  # Multicast DNS registration for macOS discovery
  multicast dns register = yes
  
  # Disable unnecessary printer services
  load printers = no
  printing = bsd
  printcap name = /dev/null
  disable spoolss = yes
  
  # Use PAM authentication - no separate Samba passwords needed!
  security = user
  passdb backend = tdbsam
  pam password change = yes
  obey pam restrictions = yes
  unix password sync = yes
  encrypt passwords = yes
  map to guest = bad user
  
  # This allows authentication against system passwords
  invalid users = root
  
  # Panic action for debugging
  panic action = /usr/share/samba/panic-action %d

# Samba users need to exist in database even with PAM authentication
samba_users:
  - name: henry
    password: "temp_password"  # This will be synced with system password
  - name: timemachine
    password: "temp_password"  # This will be synced with system password
  - name: paperless
    password: "temp_password"  # This will be synced with system password

# Samba shares configuration
samba_shares:
  - name: timemachine
    comment: "Time Machine Backup"
    path: /fs/TimeMachine
    vfs_objects:
      - name: catia
      - name: fruit
        options:
          - name: time machine
            value: "yes"
          - name: time machine max size
            value: "100G"
      - name: streams_xattr
    valid_users: timemachine
    browseable: true
    guest_ok: false
    writeable: true
    create_mode: "0644"
    directory_mode: "0755"

  - name: media
    comment: "Media Files"
    path: /fs/media
    vfs_objects:
      - name: fruit
      - name: streams_xattr
    valid_users: henry
    browseable: true
    guest_ok: false
    writeable: true
    create_mode: "0644"
    directory_mode: "0754"
    user: henry

  - name: downloads
    comment: "Downloads"
    path: /var/tmp/downloads
    vfs_objects:
      - name: fruit
      - name: streams_xattr
    valid_users: henry
    browseable: true
    guest_ok: false
    writeable: true
    create_mode: "0644"
    directory_mode: "0754"
    user: henry

  - name: scanners
    comment: "Put scanned docs here for consumption by Paperless"
    path: /fs/docker/paperless/consume
    valid_users: henry
    browseable: true
    guest_ok: false
    writeable: true
    create_mode: "0644"
    directory_mode: "0755"

  - name: incoming
    comment: "Incoming photos directory"
    path: /fs/docker/volumes/paperless/consume
    vfs_objects:
      - name: fruit
      - name: streams_xattr
    valid_users: henry
    browseable: true
    guest_ok: false
    writeable: true
    create_mode: "0644"
    directory_mode: "0754"
    user: henry
