---
# Configuration for DNS/Pi-hole server
base_hostname: pibox

# Lightweight packages for DNS server
base_packages:
  - curl
  - wget
  - vim
  - htop
  - tree
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg
  - software-properties-common
  - locales
  - tzdata
  - git
  - dnsutils  # DNS tools
  - bind9-utils  # DNS utilities
  - net-tools
  - iptables-persistent

# DNS server doesn't need ZFS tools
install_zfs_tools: false
