# sops encrypted
users:
    henry:
        password_hash: ENC[AES256_GCM,data:+Ll8/4I0ta+hJVQ4xlYigvbrKOf4Wra+P2vCUbelN3qaLi7VtttjSWvaxSKqWRRJR5WBWtsQMbikn1aMdxIL+1HXOr+bR5w6Ig==,iv:W109Dcbw7DZ1ncpNLm0ytQ8gfOaZ6/DL74aKxRGjbdg=,tag:ftqzVIVyYquEDTxtDSUe1g==,type:str]
    timemachine:
        password_hash: ENC[AES256_GCM,data:WMSSVCK6KdoazgyezaWB0ERYNEiW6KPb66x/ZlWXmCE9XehIq66I82EW9orzsFNhvqdY5HNGipeNuznD6qcvorNMUDvGurS/Ew==,iv:qMN+6uLUUYbpnIDJY8V4qWmJjOkH08QqkK/34F/F00I=,tag:1DKYMZyP+CgwlOoD0kAS6g==,type:str]
    paperless:
        password_hash: ENC[AES256_GCM,data:W/nQ8OkePXC7+jIouspmzRVgyci93BhmlpvgbExbXd8t3PnkL6F34H7ANEjD84kZ4DRiuVJOZQ94cqg3J/ibshacCB0LJd60dw==,iv:w56+3OHdBha0gfJGyBVD+WO5n44BkMAPMKaz7uEBZFM=,tag:r64hnaPtV/hbbxq/nhsQPA==,type:str]
ssh_keys:
    syncoid_private_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACAPGgI4cLzrKb4eXgXWho3AAT1itZmt7ODHuz2uveiXxwAAAJDLPP8Cyzz/
        AgAAAAtzc2gtZWQyNTUxOQAAACAPGgI4cLzrKb4eXgXWho3AAT1itZmt7ODHuz2uveiXxw
        AAAEAUYue0H7EbsI0pBrRg8FyPDgQdHS8NkibWriO3bvTWkg8aAjhwvOspvh5eBdaGjcAB
        PWK1ma3s4Me7Pa696JfHAAAAB3N5bmNvaWQBAgMEBQY=
        -----END OPENSSH PRIVATE KEY-----
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGl7Dr6eZTG7KA21Dm293hW0Mh8hsr5PawiQKMOzy7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDlJTnhWUSBQcFI0
            cTVTTm9TUmNzZmN0aFRZNFEralVFd3JiOFF0eEVpMEc2eE5NcUQ0Ckd2Z0lDdGtu
            Tmk0dkVncTRtWG53TW5SMklEMjU3cU1QVUVTWXdGQ1VEbmcKLS0tIGJOR2I0Wnhm
            N0txNzkyUjAyVGdLeFlralc1djhURGNONW91T3FHS1VSTkkKbHYS5vlL+SbCZSAd
            CCVhE/XQAJ1RZQ9TiW9f0DAZj725S6TClqu3DjHB/NlNiu9Za0xYpLXuW6oPzY5t
            qRgs/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T09:45:10Z"
    mac: ENC[AES256_GCM,data:jt53HQZz4eK2cspOaPyEMCSPW1kXofwS3FPxyd4lUjh+OeLP0lZU0rSTqcwvUsibBABRvU2QARytLBwje9cykhWrGG+ZgyYme6hNii04QMeeE8g9cp/d9aM2hFXJvLXgfLHaN55G5DbBzd4wgfuZ4HzncEcC6S3xytfWEaoetb0=,iv:cJbXnUyLHMB3gjEBsqSCvZVhx7GmQiLxtMuiXNZj3Rw=,tag:bYcJ6Dd12PbXfF77NI2sUA==,type:str]
    encrypted_regex: ^(users|secrets)$
    version: 3.10.2
