# sops encrypted
users:
    henry:
        password_hash: ENC[AES256_GCM,data:DmsJKqJ6,iv:3PuXvR+C5Wr3J/QwXngEZCCqdGSufBEKcGtzvInn51c=,tag:rrXoPR+DCXHDmQbRVpdFMA==,type:str]
        ssh_authorized_keys:
            - ENC[AES256_GCM,data:SgYLOIM+O66vebjNXEOJ+ixQ6Q==,iv:i0z2cNHkrm+leEjOxNVfBrDO3qDG80GNcl0C8ejehxI=,tag:tCcR4M0ZW09brYhq7MPHqg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGGl7Dr6eZTG7KA21Dm293hW0Mh8hsr5PawiQKMOzy7s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDlJTnhWUSBQcFI0
            cTVTTm9TUmNzZmN0aFRZNFEralVFd3JiOFF0eEVpMEc2eE5NcUQ0Ckd2Z0lDdGtu
            Tmk0dkVncTRtWG53TW5SMklEMjU3cU1QVUVTWXdGQ1VEbmcKLS0tIGJOR2I0Wnhm
            N0txNzkyUjAyVGdLeFlralc1djhURGNONW91T3FHS1VSTkkKbHYS5vlL+SbCZSAd
            CCVhE/XQAJ1RZQ9TiW9f0DAZj725S6TClqu3DjHB/NlNiu9Za0xYpLXuW6oPzY5t
            qRgs/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T09:41:49Z"
    mac: ENC[AES256_GCM,data:chrrwWM0/0etx53yhZg6fGuDXYEZvWjYqL+OlOZLhyD4yFxNMYD0l72DvCD/drXumuDR/+shHoeY0yDqWrWx0JmLv9Hd0HO9egGZLObCij/VTSZwj+YUIIXDwFtIAdv5e3m+dFe0lMKkHP2MZJNaSSRb63Qi8Cl3JQAjcYiT/Sk=,iv:VqbkFEZZEAJe9nL9X3/xZEjpqRvfOhDkFweVqwIKn0s=,tag:n1x/iYdzbpmwI7PHePeQlw==,type:str]
    encrypted_regex: ^(users|secrets)$
    version: 3.10.2
