---
- name: Restart journald
  service:
    name: systemd-journald
    state: restarted

- name: Restart systemd-hostnamed
  service:
    name: systemd-hostnamed
    state: restarted

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: restarted

- name: Restart systemd-localed
  service:
    name: systemd-localed
    state: restarted
