---
# Docker installation tasks

- name: Install Docker from official repository
  block:
    - name: Install prerequisites for Docker repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Create directory for Docker GPG key
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        update_cache: true

    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true
      when: docker_start_service | bool

    - name: Add users to docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop: "{{ docker_users }}"
      when: docker_users | length > 0

  tags: ['docker']
