- name: Install etckeeper
  apt:
    name: etckeeper
    state: present

- name: Init etckeeper repo
  command: etckeeper init
  args:
    creates: /etc/.git

- name: Auto-commit etc changes
  copy:
    dest: /etc/apt/apt.conf.d/99etckeeper
    content: 'DPkg::Post-Invoke {"etckeeper commit installed || true";};'
